services:
  - type: web
    name: rank-finance
    runtime: node
    region: oregon  # oregon | frankfurt | ohio | singapore
    plan: starter      # free | starter | standard | pro
    branch: main
    autoDeploy: true

    # Comandos de build e start com pnpm via Corepack
    buildCommand: >
      corepack enable &&
      corepack prepare pnpm@10.14.0 --activate &&
      pnpm install --frozen-lockfile --prefer-offline --prod=false &&
      pnpm run build:standalone

    startCommand: node .next/standalone/server.js

    # Variáveis de ambiente
    envVars:
      # Node.js 22 LTS para Next.js 15
      - key: NODE_VERSION
        value: "22"

      # Configuração de produção
      - key: NODE_ENV
        value: production

      # Bind to all interfaces for Render deployment (required for health checks)
      - key: HOSTNAME
        value: "0.0.0.0"

      # Note: PORT is automatically set by Render, no need to define it

      # Permitir que Next.js compacte respostas e use SWC minify
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

      # ============================================
      # Clerk Authentication (configurar via dashboard do Render)
      # sync: false significa que o valor deve ser configurado manualmente no dashboard
      # ============================================
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        sync: false

      - key: CLERK_SECRET_KEY
        sync: false

      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: "/sign-in"

      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: "/sign-up"

      - key: NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL
        value: "/"

      - key: NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL
        value: "/"

      # ============================================
      # Supabase Database (configurar via dashboard do Render)
      # ============================================
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false

      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

    # Health check endpoint (dedicated lightweight API route)
    healthCheckPath: /api/health
