services:
  - type: web
    name: rank-finance
    runtime: node
    region: oregon  # oregon | frankfurt | ohio | singapore
    plan: starter      # free | starter | standard | pro
    branch: main
    autoDeploy: true

    # Comandos de build e start com pnpm via Corepack
    buildCommand: |
      corepack enable
      corepack prepare pnpm@10.14.0 --activate
      pnpm install --frozen-lockfile --prefer-offline --prod=false
      pnpm run build

    startCommand: |
      corepack enable
      corepack prepare pnpm@10.14.0 --activate
      pnpm run start

    # Variáveis de ambiente
    envVars:
      # Node.js 22 LTS para Next.js 15
      - key: NODE_VERSION
        value: "22"

      # Configuração de produção
      - key: NODE_ENV
        value: production

      # Permitir que Next.js compacte respostas e use SWC minify
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"

      # Credenciais do Supabase (configurar via dashboard do Render)
      # sync: false significa que o valor deve ser configurado manualmente no dashboard
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false

      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

    # Health check endpoint (use a lightweight static route to avoid SSR on deploy)
    healthCheckPath: /robots.txt
